title: "ПакТочка — упаковочные материалы"
description: "Оптовая продажа упаковочных материалов: коробки, пакеты, пленка, скотч. Екатеринбург."
url: "https://packtochka.ru"
baseurl: ""
theme: minima

collections:
  products:
    output: true
    permalink: /katalog/:categories/:slug/

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: product
      sitemap: true

plugins:
  - jekyll-sitemap

sass:
  style: compressed
markdown: kramdown

formspree_form_id: mzzvybwq     # <-- замени на свой реальный ID из Formspree (после /f/)
thankyou_url: /spasibo/ 
