
# Добавляйте товары сюда. Каждая запись = товар.
# category варианты: korobki, pakety, skotch, plenka, prochie
- name: Коробка гофрокартон 10×10×10 см, бурый, Т-23Б
  sku: K-10x10x10-T23B
  price: 9
  unit: "руб/шт при партии 100 шт"
  min_qty: 100
  category: korobki
  slug: korobka-10x10x10-t23b
  short: Прочная четырёхклапанная коробка для мелких товаров, сувениров и отправлений.
  specs:
    - 3-х слойный гофрокартон Т23Б
    - Цвет: бурый
    - Размеры: 10×10×10 см
    - Тип: четырёхклапанная, FEFCO 0201
  images:
    - /assets/img/korobka-10-10-10.jpg

- name: Пакет курьерский 250×350 мм, с клеевым клапаном, 60 мкм
  sku: PK-250x350-60
  price: 4.5
  unit: "руб/шт при партии 100 шт"
  min_qty: 100
  category: pakety
  slug: paket-kurierskiy-250x350-60
  short: Надёжный пакет для отправки заказов, непрозрачный, с усиленным швом.
  specs:
    - Толщина: 60 мкм
    - Цвет: серый/чёрный
    - Клапан самоклеящийся
  images:
    - /assets/img/paket-250x350.jpg
