- name: Коробка картонная 150x120x100 мм
  category: korobki
  slug: korobka-150x120x100
  price: '9.5'
  unit: ₽/шт
  short: Картонная коробка бурого цвета из гофрокартона Т23Б.
  images:
  - /assets/img/korobka-150x120x100.png
  min_order: 100 шт
- name: Коробка почтовая 150x150x150 мм
  category: korobki
  slug: korobka-150x150x150
  price: '20'
  unit: ₽/шт
  short: Картонная коробка бурого цвета четырехклапанная.
  images:
  - /assets/img/korobka-150x150x150.png 
  min_order: 100 шт
- name: Коробка картонная 100х100х100 мм
  category: korobki
  slug: korobka-100x100x100
  price: '9'
  unit: ₽/шт
  short: Картонная коробка бурого цвета четырехклапанная.
  images:
  - /assets/img/korobka-100x100x100.png
  min_order: 100 шт
- name: Коробка картонная 190х150х180 мм
  category: korobki
  slug: korobka-190x150x180
  price: '15'
  unit: ₽/шт
  short: Картонная коробка бурого цвета четырехклапанная.
  images:
  - /assets/img/korobka-190x150x180.png
  min_order: 100 шт
- name: Коробка картонная 200х120х120 мм
  category: korobki
  slug: korobka-200x120x120
  price: '12.5'
  unit: ₽/шт
  short: Картонная коробка бурого цвета четырехклапанная.
  images:
  - /assets/img/korobka-200x120x120.png
  min_order: 100 шт
- name: Коробка картонная 250х150х150 мм
  category: korobki
  slug: korobka-250x150x150
  price: '16.5'
  unit: ₽/шт
  short: Картонная коробка бурого цвета четырехклапанная.
  images:
  - /assets/img/korobka-250x125x150.png
  min_order: 100 шт
- name: Пакет курьерский 100x150 мм
  category: pakety
  slug: paket-kurierski-100x150
  price: '1.5'
  unit: ₽/шт
  short: Белый пакет с клеевым клапаном 40мм, толщина 40 мкм.
  images:
  - /assets/img/paket-kurierski-100x150.png
  min_order: 100 шт
- name: Пакет курьерский 150x210 мм
  category: pakety
  slug: paket-kurierski-150x210
  price: '2'
  unit: ₽/шт
  short: Белый пакет с клеевым клапаном 40мм, толщина 50 мкм.
  images:
  - /assets/img/paket-kurierski-150x210.png
  min_order: 100 шт
- name: Пакет курьерский 170x240 мм
  category: pakety
  slug: paket-kurierski-170x240
  price: '2.2'
  unit: ₽/шт
  short: Белый пакет с клеевым клапаном 40мм, толщина 50 мкм.
  images:
  - /assets/img/paket-kurierski-170x240.png
  min_order: 100 шт
- name: Пакет курьерский 190x240 мм
  category: pakety
  slug: paket-kurierski-190x240
  price: '2.5'
  unit: ₽/шт
  short: Белый пакет с клеевым клапаном 40мм, толщина 40 мкм.
  images:
  - /assets/img/paket-kurierski-190x240.png
  min_order: 100 шт
- name: Пакет курьерский 240x320 мм
  category: pakety
  slug: paket-kurierski-240x320
  price: '3.5'
  unit: ₽/шт
  short: Белый пакет с клеевым клапаном 40мм, толщина 40 мкм.
  images:
  - /assets/img/paket-kurierski-240x320.png
  min_order: 100 шт
- name: Пакет курьерский 300x400 мм
  category: pakety
  slug: paket-kurierski-300x400
  price: '5'
  unit: ₽/шт
  short: Белый пакет с клеевым клапаном 40мм, толщина 40 мкм.
  images:
  - /assets/img/paket-kurierski-300x400.png
  min_order: 100 шт
- name: Пакет курьерский 400x500 мм
  category: pakety
  slug: paket-kurierski-400x500
  price: '7.5'
  unit: ₽/шт
  short: Белый пакет с клеевым клапаном 40мм, толщина 40 мкм.
  images:
  - /assets/img/paket-kurierski-400x500.png
  min_order: 100 шт
- name: Пакет курьерский 400x600 мм
  category: pakety
  slug: paket-kurierski-400x600
  price: '8.5'
  unit: ₽/шт
  short: Белый пакет с клеевым клапаном 40мм, толщина 40 мкм.
  images:
  - /assets/img/paket-kurierski-400x600.png
  min_order: 100 шт
- name: Скотч упаковочный 50мм x 150м, прозрачный
  category: skotch
  slug: skotch-prozrachny-150m-52mkm
  price: '150'
  unit: ₽/рулон
  short: Универсальный прочный скотч для упаковки коробок и посылок.
  images:
  - /assets/img/skotch-prozrachny-150m-52mkm.png
  min_order: 6 рулонов
- name: Скотч коричневый 48 мм × 66 м
  category: skotch
  slug: skotch-kor-48x66
  sku: S4866K
  price: '45'
  unit: ₽/рулон
  short: Клейкая лента для коробок бурого цвета.
  images:
  - /assets/images/demo/placeholder.jpg
  min_order: 36 рулонов
- name: Скотч с логотипом на заказ
  category: skotch
  slug: skotch-logo
  sku: SLOGO
  price: от 70
  unit: ₽/рулон
  short: Лента с печатью логотипа клиента.
  images:
  - /assets/images/demo/placeholder.jpg
  min_order: 36 рулонов
- name: Стрейч-плёнка прозрачная 17 мкм
  category: plenka
  slug: streych-proz-17
  sku: SP17
  price: '450'
  unit: ₽/рулон
  short: Для ручной упаковки грузов.
  images:
  - /assets/images/demo/placeholder.jpg
  min_order: 6 рулонов
- name: Стрейч-плёнка чёрная 23 мкм, 500мм, 1.8кг
  category: plenka
  slug: streych-plenka-chernaya-1-8-kg
  price: '480'
  unit: ₽/рулон
  short: Скрывает содержимое груза, повышенная прочность, втулка 500мм, первичка.
  images:
  - /assets/img/streych-plenka-chernaya-1-8-kg.png
  min_order: 6 рулонов
- name: Стрейч-плёнка прозрачная 23 мкм, 500мм, 1.7кг
  category: plenka
  slug: streych-plenka-prozrachnaya-1-7-kg
  price: '480'
  unit: ₽/рулон
  short: Скрывает содержимое груза, повышенная прочность, втулка 500мм, первичка.
  images:
  - /assets/img/streych-plenka-prozrachnaya-1-7-kg.png
  min_order: 6 рулонов
- name: Стрейч-плёнка машинная 23 мкм
  category: plenka
  slug: streych-mash-23
  sku: SP23M
  price: '500'
  unit: ₽/рулон
  short: Для автоматической обмотки паллет.
  images:
  - /assets/images/demo/placeholder.jpg
  min_order: 6 рулонов
- name: Воздушно-пузырчатая плёнка 1,2×100 м
  category: prochie
  slug: puzyrka-1.2x100
  sku: BP120100
  price: '1800'
  unit: ₽/рулон
  short: Двухслойная, диаметр пузырька 10 мм.
  images:
  - /assets/images/demo/placeholder.jpg
  min_order: 1 рулон
- name: Гофрорулон 1,05×20 м
  category: prochie
  slug: gofrorulon-1.05x20
  sku: GR10520
  price: '600'
  unit: ₽/рулон
  short: Гофрокартон в рулоне для упаковки.
  images:
  - /assets/images/demo/placeholder.jpg
  min_order: 1 рулон
- name: БОПП пакет 200×300 мм
  category: prochie
  slug: bopp-200x300
  sku: B200300
  price: '2.5'
  unit: ₽/шт
  short: Прозрачный пакет для мелких товаров.
  images:
  - /assets/images/demo/placeholder.jpg
  min_order: 100 шт
